### ISSUE TITLE
Implement a vmlinux retention policy

### ISSUE THREAD

**Issue by xmkg** [canonical/hotkdump#3]
This is a follow-up ticket to #2. As there is a high possibility for `hotkdump` to process several `kdump` files that'd need the exact same `vmlinux` image, keeping `vmlinux` files around is a good idea to avoid downloading them from scratch every time. Keeping them around forever is also wasteful, so ideally `hotkdump` should have a `vmlinux-dir` retention policy that automatically erases the least recently accessed `vmlinux` file when the size of `vmlinux-dir` exceeds a certain threshold, e.g. >= 50GB.

**Comment by mustafakemalgilor** [comment]
Closed via #18.
